package com.phy.app.beans;

import java.util.HashMap;
import java.util.Map;

public class GattUuidInfo {
    public  static  Map<String,String> uuidMap=new HashMap<>();
    public static Map<String,String> charUuidMap=new HashMap<>();

    static {
        uuidMap.put("1800","Generic Access");
        uuidMap.put("1801","Generic Attribute");
        uuidMap.put("1802","Immediate Alert");
        uuidMap.put("1803","Link Loss");
        uuidMap.put("1804","Tx Power");
        uuidMap.put("1805","Current Time Service");
        uuidMap.put("1806","Reference Time Update Service");
        uuidMap.put("1807","Next DST Change Service");
        uuidMap.put("1808","Glucose");
        uuidMap.put("1809","Health Thermometer");
        uuidMap.put("180a","Device Information");
        uuidMap.put("180d","Heart Rate");
        uuidMap.put("180e","Phone Alert Status Service");
        uuidMap.put("180f","Battery Service");
        uuidMap.put("1810","Blood Pressure");
        uuidMap.put("1811","Alert Notification Service");
        uuidMap.put("1812","Human Interface Device");
        uuidMap.put("1813","Scan Parameters");
        uuidMap.put("1814","Running Speed and Cadence");
        uuidMap.put("1815","Automation IO");
        uuidMap.put("1816","Cycling Speed and Cadence");
        uuidMap.put("1818","Cycling Power");
        uuidMap.put("1819","Location and Navigation");
        uuidMap.put("181a","Environmental Sensing");
        uuidMap.put("181b","Body Composition");
        uuidMap.put("181c","User Data");
        uuidMap.put("181d","Weight Scale");
        uuidMap.put("181e","Bond Management Service");
        uuidMap.put("181f","Continuous Glucose Monitoring");
        uuidMap.put("1820","Internet Protocol Support Service");
        uuidMap.put("1821","Indoor Positioning");
        uuidMap.put("1822","Pulse Oximetry Service");
        uuidMap.put("1823","HTTP Proxy");
        uuidMap.put("1824","Transport Discovery");
        uuidMap.put("1825","Object Transfer Service");
        uuidMap.put("1826","Fitness Machine");
        uuidMap.put("1827","Mesh Provisioning Service");
        uuidMap.put("1828","Mesh Proxy Service");
        uuidMap.put("1829","Reconnection Configuration");

        charUuidMap.put("2a00","Device Name");
        charUuidMap.put("2a01","Appearance");
        charUuidMap.put("2a02","Peripheral Privacy Flag");
        charUuidMap.put("2a03","Reconnection Address");
        charUuidMap.put("2a04","Peripheral Preferred Connection Parameters");
        charUuidMap.put("2a05","Service Changed");
        charUuidMap.put("2a06","Alert Level");
        charUuidMap.put("2a07","Tx Power Level");
        charUuidMap.put("2a08","Date Time");
        charUuidMap.put("2a09","Day of Week");
        charUuidMap.put("2a0a","Day Date Time");
        charUuidMap.put("2a0b","Exact Time 100");
        charUuidMap.put("2a0c","Exact Time 256");
        charUuidMap.put("2a0d","DST Offset");
        charUuidMap.put("2a0e","Time Zone");
        charUuidMap.put("2a0f","Local Time Information");
        charUuidMap.put("2a10","Secondary Time Zone");
        charUuidMap.put("2a11","Time with DST");
        charUuidMap.put("2a12","Time Accuracy");
        charUuidMap.put("2a13","Time Source");
        charUuidMap.put("2a14","Reference Time Information");
        charUuidMap.put("2a15","Time Broadcast");
        charUuidMap.put("2a16","Time Update Control Point");
        charUuidMap.put("2a17","Time Update State");
        charUuidMap.put("2a18","Glucose Measurement");
        charUuidMap.put("2a19","Battery Level");
        charUuidMap.put("2a1a","Battery Power State");
        charUuidMap.put("2a1b","Battery Level State");
        charUuidMap.put("2a1c","Temperature Measurement");
        charUuidMap.put("2a1d","Temperature Type");
        charUuidMap.put("2a1e","Intermediate Temperature");
        charUuidMap.put("2a1f","Temperature Celsius");
        charUuidMap.put("2a20","Temperature Fahrenheit");
        charUuidMap.put("2a21","Measurement Interval");
        charUuidMap.put("2a22","Boot Keyboard Input Report");
        charUuidMap.put("2a23","System ID");
        charUuidMap.put("2a24","Model Number String");
        charUuidMap.put("2a25","Serial Number String");
        charUuidMap.put("2a26","Firmware Revision String");
        charUuidMap.put("2a27","Hardware Revision String");
        charUuidMap.put("2a28","Software Revision String");
        charUuidMap.put("2a29","Manufacturer Name String");
        charUuidMap.put("2a2a","Regulatory Certification Data List");
        charUuidMap.put("2a2b","Current Time");
        charUuidMap.put("2a2c","Magnetic Declination");
        charUuidMap.put("2a2f","Position 2D");
        charUuidMap.put("2a30","Position 3D");
        charUuidMap.put("2a31","Scan Refresh");
        charUuidMap.put("2a32","Boot Keyboard Output Report");
        charUuidMap.put("2a33","Boot Mouse Input Report");
        charUuidMap.put("2a34","Glucose Measurement Context");
        charUuidMap.put("2a35","Blood Pressure Measurement");
        charUuidMap.put("2a36","Intermediate Cuff Pressure");
        charUuidMap.put("2a37","Heart Rate Measurement");
        charUuidMap.put("2a38","Body Sensor Location");
        charUuidMap.put("2a39","Heart Rate Control Point");
        charUuidMap.put("2a3a","Removable");
        charUuidMap.put("2a3b","Service Required");
        charUuidMap.put("2a3c","Scientific Temperature Celsius");
        charUuidMap.put("2a3d","String");
        charUuidMap.put("2a3f","Alert Status");
        charUuidMap.put("2a40","Ringer Control point");
        charUuidMap.put("2a41","Ringer Setting");
        charUuidMap.put("2a42","Alert Category ID Bit Mask");
        charUuidMap.put("2a43","Alert Category ID");
        charUuidMap.put("2a44","Alert Notification Control Point");
        charUuidMap.put("2a45","Unread Alert Status");
        charUuidMap.put("2a46","New Alert");
        charUuidMap.put("2a47","Supported New Alert Category");
        charUuidMap.put("2a48","Supported Unread Alert Category");
        charUuidMap.put("2a49","Blood Pressure Feature");
        charUuidMap.put("2a4a","HID Information");
        charUuidMap.put("2a4b","Report Map");
        charUuidMap.put("2a4c","HID Control Point");
        charUuidMap.put("2a4d","Report");
        charUuidMap.put("2a4e","Protocol Mode");
        charUuidMap.put("2a4f","Scan Interval Window");
        charUuidMap.put("2a50","PnP ID");
        charUuidMap.put("2a51","Glucose Feature");
        charUuidMap.put("2a52","Record Access Control Point");
        charUuidMap.put("2a53","RSC Measurement");
        charUuidMap.put("2a54","RSC Feature");
        charUuidMap.put("2a55","SC Control Point");
        charUuidMap.put("2a56","Digital");
        charUuidMap.put("2a57","Digital Output");
        charUuidMap.put("2a58","Analog");
        charUuidMap.put("2a59","Analog Output");
        charUuidMap.put("2a5a","Aggregate");
        charUuidMap.put("2a5b","CSC Measurement");
        charUuidMap.put("2a5c","CSC Feature");
        charUuidMap.put("2a5d","Sensor Location");
        charUuidMap.put("2a5e","PLX Spot-Check Measurement");
        charUuidMap.put("2a5f","PLX Continuous Measurement");
        charUuidMap.put("2a60","PLX Features");
        charUuidMap.put("2a62","Pulse Oximetry Control Point");
        charUuidMap.put("2a63","Cycling Power Measurement");
        charUuidMap.put("2a64","Cycling Power Vector");
        charUuidMap.put("2a65","Cycling Power Feature");
        charUuidMap.put("2a66","Cycling Power Control Point");
        charUuidMap.put("2a67","Location and Speed Characteristic");
        charUuidMap.put("2a68","Navigation");
        charUuidMap.put("2a69","Position Quality");
        charUuidMap.put("2a6a","LN Feature");
        charUuidMap.put("2a6b","LN Control Point");
        charUuidMap.put("2a6c","Elevation");
        charUuidMap.put("2a6d","Pressure");
        charUuidMap.put("2a6e","Temperature");
        charUuidMap.put("2a6f","Humidity");
        charUuidMap.put("2a70","True Wind Speed");
        charUuidMap.put("2a71","True Wind Direction");
        charUuidMap.put("2a72","Apparent Wind Speed");
        charUuidMap.put("2a73","Apparent Wind Direction");
        charUuidMap.put("2a74","Gust Factor");
        charUuidMap.put("2a75","Pollen Concentration");
        charUuidMap.put("2a76","UV Index");
        charUuidMap.put("2a77","Irradiance");
        charUuidMap.put("2a78","Rainfall");
        charUuidMap.put("2a79","Wind Chill");
        charUuidMap.put("2a7a","Heat Index");
        charUuidMap.put("2a7b","Dew Point");
        charUuidMap.put("2a7d","Descriptor Value Changed");
        charUuidMap.put("2a7e","Aerobic Heart Rate Lower Limit");
        charUuidMap.put("2a7f","Aerobic Threshold");
        charUuidMap.put("2a80","Age");
        charUuidMap.put("2a81","Anaerobic Heart Rate Lower Limit");
        charUuidMap.put("2a82","Anaerobic Heart Rate Upper Limit");
        charUuidMap.put("2a83","Anaerobic Threshold");
        charUuidMap.put("2a84","Aerobic Heart Rate Upper Limit");
        charUuidMap.put("2a85","Date of Birth");
        charUuidMap.put("2a86","Date of Threshold Assessment");
        charUuidMap.put("2a87","Email Address");
        charUuidMap.put("2a88","Fat Burn Heart Rate Lower Limit");
        charUuidMap.put("2a89","Fat Burn Heart Rate Upper");
        charUuidMap.put("2a8a","First Name");
        charUuidMap.put("2a8b","Five Zone Heart Rate Limits");
        charUuidMap.put("2a8c","Gender");
        charUuidMap.put("2a8d","Heart Rate Max");
        charUuidMap.put("2a8e","Height");
        charUuidMap.put("2a8f","Hip Circumference");
        charUuidMap.put("2a90","Last Name");
        charUuidMap.put("2a91","Maximum Recommended Heart Rate");
        charUuidMap.put("2a92","Resting Heart Rate");
        charUuidMap.put("2a93","Sport Type for Aerobic and Anaerobic Thresholds");
        charUuidMap.put("2a94","Three Zone Heart Rate Limits");
        charUuidMap.put("2a95","Two Zone Heart Rate Limit");
        charUuidMap.put("2a96","VO2 Max");
        charUuidMap.put("2a97","Waist Circumference");
        charUuidMap.put("2a98","Weight");
        charUuidMap.put("2a99","Database Change Increment");
        charUuidMap.put("2a9a","User Index");
        charUuidMap.put("2a9b","Body Composition Feature");
        charUuidMap.put("2a9c","Body Composition Measurement");
        charUuidMap.put("2a9d","Weight Measurement");
        charUuidMap.put("2a9e","Weight Scale Feature");
        charUuidMap.put("2a9f","User Control Point");
        charUuidMap.put("2aa0","Magnetic Flux Density–2D");
        charUuidMap.put("2aa1","Magnetic Flux Density–3D");
        charUuidMap.put("2aa2","Language");
        charUuidMap.put("2aa3","Barometric Pressure Trend");
        charUuidMap.put("2aa4","Bond Management Control Point");
        charUuidMap.put("2aa5","Bond Management Features");
        charUuidMap.put("2aa6","Central Address Resolution");
        charUuidMap.put("2aa7","CGM Measurement");
        charUuidMap.put("2aa8","CGM Feature");
        charUuidMap.put("2aa9","CGM Status");
        charUuidMap.put("2aaa","CGM Session Start Time");
        charUuidMap.put("2aab","CGM Session Run Time");
        charUuidMap.put("2aac","CGM Specific Ops Control Point");
        charUuidMap.put("2aad","Indoor Positioning Configuration");
        charUuidMap.put("2aae","Latitude");
        charUuidMap.put("2aaf","Longitude");
        charUuidMap.put("2ab0","Local North Coordinate");
        charUuidMap.put("2ab1","Local East Coordinate");
        charUuidMap.put("2ab2","Floor Number");
        charUuidMap.put("2ab3","Altitude");
        charUuidMap.put("2ab4","Uncertainty");
        charUuidMap.put("2ab5","Location Name");
        charUuidMap.put("2ab6","URI");
        charUuidMap.put("2ab7","HTTP Headers");
        charUuidMap.put("2ab8","HTTP Status Code");
        charUuidMap.put("2ab9","HTTP Entity Body");
        charUuidMap.put("2aba","HTTP Control Point");
        charUuidMap.put("2abb","HTTPS Security");
        charUuidMap.put("2abc","TDS Control Point");
        charUuidMap.put("2abd","OTS Feature");
        charUuidMap.put("2abe","Object Name");
        charUuidMap.put("2abf","Object Type");
        charUuidMap.put("2ac0","Object Size");
        charUuidMap.put("2ac1","Object First-Created");
        charUuidMap.put("2ac2","Object Last-Modified");
        charUuidMap.put("2ac3","Object ID");
        charUuidMap.put("2ac4","Object Properties");
        charUuidMap.put("2ac5","Object Action Control Point");
        charUuidMap.put("2ac6","Object List Control Point");
        charUuidMap.put("2ac7","Object List Filter");
        charUuidMap.put("2ac8","Object Changed");
        charUuidMap.put("2ac9","Resolvable Private Address Only");
        charUuidMap.put("2acc","Fitness Machine Feature");
        charUuidMap.put("2acd","Treadmill Data");
        charUuidMap.put("2ace","Cross Trainer Data");
        charUuidMap.put("2acf","Step Climber Data");
        charUuidMap.put("2ad0","Stair Climber Data");
        charUuidMap.put("2ad1","Rower Data");
        charUuidMap.put("2ad2","Indoor Bike Data");
        charUuidMap.put("2ad3","Training Status");
        charUuidMap.put("2ad4","Supported Speed Range");
        charUuidMap.put("2ad5","Supported Inclination Range");
        charUuidMap.put("2ad6","Supported Resistance Level Range");
        charUuidMap.put("2ad7","Supported Heart Rate Range");
        charUuidMap.put("2ad8","Supported Power Range");
        charUuidMap.put("2ad9","Fitness Machine Control Point");
        charUuidMap.put("2ada","Fitness Machine Status");
        charUuidMap.put("2aed","Date UTC");
    }
}
